public/css/style.css
public/menu-subscribe.html
public/src/mechu.js
public/src/menu-subscribe.js

1. 버튼 정렬 및 CSS를 적용하였습니다.
2. 준석님과의 논의에 따라 DB에서 가져온 음식 정보를 이미지 밑에 표시되도록 수정하였습니다.
3. 기타 자잘한 프론트엔드 부분을 수정하였습니다.

Feature front menu subscribe

---

public/preference.html
public/src/preference.js

선호도 조사 GET 프론트-백엔드 연결
** 프론트엔드단에서 각 data-filter가 순서가 바뀌는 문제 해결해야함

feat. 선호도 조사 GET

---

public/blog-details.html
public/feed.html
public/foodlist-admin.html
public/foodlist.html
public/index.html
public/kakaomap-api.html
public/menu-subscribe.html
public/preference.html
public/shop-details.html
public/src/index.js
public/src/kakaomap-api.js
public/src/mechu.js
public/src/menu-subscribe.js
public/terms.html

메뉴 추천받기를 한 후 메뉴가 나오면
맛집 추천받기 버튼이 생성되고 맛집추천받기를 클릭하면
지도 api 페이지 새창이 뜸
그러나 추천 받은 메뉴를 매개변수로 함수를 호출하는 데에는 실패

feat. 메뉴 추천페이지 지도 api 띄우기 구현

---

public/css/style.css
public/index.html
public/mypage.html
public/src/index.js

1. 로그인 시 로그아웃 버튼 생성
2. 로그아웃 시 로그인 모달 생성되는 문제 수정
3. 로그인 후 다른페이지>홈페이지 이동 시 로그인 버튼이 보이는 문제 수정
4. 마이페이지 버튼 css수정
5. useful링크에 마이페이지 등록

fix: 프론트엔드 작업

---

public/css/modaltest.css
public/css/style.css
public/feed-create.html
public/feed.html
public/foodlist-admin.html
public/foodlist.html
public/index.html
public/kakaomap-api.html
public/menu-subscribe.html
public/modaltest.html
public/mypage.html
public/preference.html
public/src/index.js

모달 창 / 탑바 / footer 전체적으로 수정
각 창마다 회원가입/로그인 버튼 볼 수 있음
회원가입 - 로그인 연결 중
: 메일 인증번호 발송 / 메일 인증은 성공
=> 비밀번호 hash가 안되는 듯 함

fix. 모달 창/ 탑바 / footer 전체적으로 수정

---

public/favoritelist.html
public/feed-detail.html
public/feed.html
public/foodlist-admin.html
public/foodlist.html
public/menu-subscribe.html
public/mypage.html
public/preference.html
public/src/preference.js

1. 회원가입/로그인/로그아웃 기능 모든 페이지 적용(상세 아직 안됨) 
2. 홈페이지 탑바 오늘의 메뉴 랜덤메뉴 추천 대부분의 페이지에 적용 완료

fix: 회원가입/로그인/로그아웃 기능 모든 페이지 적용

---

public/mypage.html

로그인/로그아웃 기능을 제외하고 살려서 해당 기능을 추가로 머지합니다.

마이페이지 로그인/로그아웃 기능 추가 커밋

---

public/index.html

https용 axios 스크립트 index.html에 추가
메인에 머지하고 테스트 필요

add: https용 axios 스크립트 추가

---

public/feed-create.html
public/feed-detail.html
public/index.html
public/mypage.html
public/preference.html

fix: axios 라이브러리 통일

---

public/src/user.js
src/users/users.controller.ts
src/users/users.service.ts

1. 회원가입 시 액세스토큰을 발급하도록 로직 변경
2. 회원가입, 로그인시 얼럿 undifiend 뜨던 문제 수정

fix: 유저 에러 해결

---

public/feed.html
public/menu-subscribe.html
public/mypage.html
public/preference.html
public/src/checkLogin.js
public/terms.html
src/users/users.controller.ts

1. 로그인이 되지 않았을 때 홈 페이지 외 모든 페이지 접근 제한
2. 로그아웃 메시지 변경 (로그아웃 완료)

fix: 로그인이 되지 않았을 때 홈 페이지 외 모든 페이지 접근 제한

---

public/index.html

클래스값이 대문자로 되어 있어서 소문자로 변경하였습니다.

회원가입 버튼 모달 정상화

---

src/auth/auth.middleware.ts
src/users/users.service.ts

1. 미들웨어 받아올 때 액세스토큰, 리프레시토큰을 받아오게 수정
2. 유저서비스 메일 인증 로직 살림

fix: 미들웨어, 유저 서비스 수정

---

src/users/users.controller.ts

회원가입 시 dto정보를 받아오도록 수정했습니다. 에러핸들링은 추후 수정

fix: 회원가입 시 dto정보 받아오도록 수정

---

public/src/admin.js
public/src/checkLogin.js
public/src/dailymenu.js
public/src/favoritelist.js
public/src/feed-create.js
public/src/feed-detail.js
public/src/feed.js
public/src/foodlist.js
public/src/index.js
public/src/kakaomap-api.js
public/src/menu-button.js
public/src/menu-subscribe.js
public/src/mypage.js
public/src/preference.js
public/src/user.js

메인브랜치 엔드포인트 변경 (hotfix 브랜치에서 작업)

hotfix: 엔드포인트 변경

---

public/mypage.html
public/src/mypage.js
src/users/dto/update.user.dto.ts
src/users/users.service.ts

fix: 마이페이지 기능 수정

---

public/css/feed.css
public/feed-create.html
public/foodlist.html
public/menu-subscribe.html
public/src/feed-create.js
public/src/feed.js
public/src/user.js
src/comments/comments.service.ts
src/feeds/feeds.service.ts

회원탈퇴 에러메시지 수정
메뉴추천 기능 안되는것수정
피드작성 css적용(버튼<>게시물 공백처리)
피드 작성 시 월일, 하트 나오던 문제 수정
피드 작성 안내문 강화 (이미지를 등록해주셔야 생성이 가능합니다.)
피드 작성 실패 에러메시지 수정
메뉴 툴팁버튼 툴팁수정
댓글 최신순 정렬

fix: 에러 수정

---

public/src/feed-detail.js
public/src/mypage.js

fix. https 적용 안된부분 수정

---

public/css/kakaomap.css
public/css/preference.css
public/kakaomap-api.html
public/src/checkLogin.js
public/src/feed-detail.js
public/src/feed.js
public/src/user.js
public/terms.html

kakaomap-api.html 102번째줄 버튼 추가 O
kakaomap.css 전체 교체  O
feed-detail.js formateDate 함수 전체 교체 60번째 줄 O
feed-detail.js 192번째줄 O
feed.js formateDate 함수 전체교체 20번째줄 O
checkLogin.js 4번째 줄 교체 O
user.js 130번째 줄 교체  O
terms.html 29번째부터 가입모달, 로그인모달 추가 O

fix. 프론트쪽 오류 수정

---

public/css/favoritelist.css
public/css/feed-detail.css
public/css/foodlist.css
public/css/menu-subscribe.css
public/css/mypage.css
public/css/preference.css
public/css/style.css
public/favoritelist.html
public/feed-create.html
public/feed-detail.html
public/feed.html
public/foodlist-admin.html
public/foodlist.html
public/index.html
public/kakaomap-api.html
public/menu-subscribe.html
public/mypage.html
public/preference.html
public/src/checkLogin.js
public/src/feed-create.js
public/src/foodlist-admin.js
public/src/foodlist.js
public/src/menu-subscribe.js
public/src/user.js

1. 버튼 수정(다 통일시켜놓음)
2. 페이지 폰트 적용
3. 페이지 로그인체크, 페이지별 모달 적용
4. 기타 CSS및 html 수정 작업

fix: 프론트엔드 수정작업
